version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  unittest_py311:
    docker:
      - image: cimg/python:3.11
    environment:
      PYTEST_ADDOPTS: --cov-report=xml:test-reports/coverage.xml --junitxml=test-reports/junit.xml
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}-py311
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Fix arango-orm dependencies
          command: |
            poetry run pip install six
      - run:
          name: Run tests
          command: |
            poetry run pytest -vv --cov=flask_arango_orm tests/
      - save_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}-py311
          paths:
            - "~/.cache/pypoetry"
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
  unittest_py312:
    docker:
      - image: cimg/python:3.12
    environment:
      PYTEST_ADDOPTS: --cov-report=xml:test-reports/coverage.xml --junitxml=test-reports/junit.xml
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}-py312
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Fix arango-orm dependencies
          command: |
            poetry run pip install six
      - run:
          name: Run tests
          command: |
            poetry run pytest -vv --cov=flask_arango_orm tests/
      - save_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}-py312
          paths:
            - "~/.cache/pypoetry"
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  build_test_publish:
    jobs:
      - unittest_py311
      - unittest_py312
