version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  unittest_py38:
    docker:
      - image: cimg/python:3.8
    environment:
      PYTEST_ADDOPTS: --cov-report=xml:test-reports/coverage.xml --junitxml=test-reports/junit.xml
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}-py38
      - run:
          name: Fix arango-orm dependencies
          command: |
            pip install six
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            poetry run pytest -vv --cov=src tests/
      - save_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}-py38
          paths:
            - "~/.cache/pypoetry"
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  build_test_publish_py38:
    jobs:
      - unittest_py38
