version: 2.1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - dependencies:
          filters:
            tags:
              only: /.*/
      - test:
          version: "3.2"
          requires:
            - dependencies:
                - version: "3.2"
      - test:
          version: "3.3"
          requires:
            - dependencies:
                - version: "3.3"
      - test:
          version: "3.4"
          requires:
            - dependencies:
                - version: "3.4"
      - test:
          version: "3.5"
          requires:
            - dependencies:
                - version: "3.5"
      - test:
          version: "3.6"
          requires:
            - dependencies:
                - version: "3.6"
      - test:
          version: "3.7"
          requires:
            - dependencies:
                - version: "3.7"
      - pypi:
          requires:
            - dependencies
            - test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

jobs:

  dependencies:
    parameters:
      version:
        type: string
        default: "3.7"
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}-<< parameters.version >>
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}-<< parameters.version >>
          paths:
            - "venv"

  test:
    parameters:
      version:
        type: string
        default: "3.7"
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}-<< parameters.version >>
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
      - run:
          name: Smoke Test Install
          command: |
            python --version
            python setup.py install

  pypi:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}-3.7
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py build
      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = ravenoak" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*
